

// DOMINGO
eventos[0] = {
	'20:00': {'title': 'MEGADROP', 'message': 'Todos os servers, lorencia (140, 125)'},

	'00:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'02:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'04:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'06:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'08:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'10:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'12:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'14:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'16:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'18:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'20:29': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'22:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},

	'01:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'03:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'05:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'07:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'09:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'11:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'13:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'15:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'17:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'18:59': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'21:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'23:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},

	'01:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'03:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'05:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'07:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'09:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'11:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'13:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'15:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'17:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'19:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'21:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'23:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},

	'00:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'04:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'08:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'12:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'16:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'20:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},

	'00:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'04:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'08:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'12:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'16:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'20:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},

	'00:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'04:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'08:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'12:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'16:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'20:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},

	'00:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'04:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'08:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'12:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'16:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'20:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},

	'02:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'06:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'10:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'14:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'18:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'22:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},

	'01:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'05:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'09:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'13:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'17:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'21:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},

	'16:00': {'title': 'Kundun', 'message': 'Precisa de convite: Lost Map (Kalima)'},
	'21:00': {'title': 'Erohin', 'message': 'LAND OF TRIALS, precisa ser membro de guild vencedora do CS'},
	'18:00': {'title': 'Medusa', 'message': 'PEACE SWAMP'},
	'20:30': {'title': 'Balgass', 'message': 'RAKLION HATCHERY'},
	'21:00': {'title': 'Tesouro Loren', 'message': 'Todos os servers'},
	'14:59': {'title': 'Tesouro Dung', 'message': 'Todos os servers'},

	'23:00': {'title': 'Invocação de boss', 'message': 'Server 1'},

	'19:00': {'title': 'Ataque zumbi', 'message': 'Server 1'},
}

// SEGUNDA
eventos[1] = {
	'20:00': {'title': 'MEGADROP', 'message': 'Todos os servers, lorencia (140, 125)'},
	'00:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'02:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'04:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'06:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'08:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'10:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'12:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'14:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'16:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'18:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'20:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'22:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},

	'01:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'03:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'05:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'07:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'09:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'11:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'13:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'15:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'17:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'19:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'21:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'23:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},

	'01:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'03:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'05:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'07:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'09:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'11:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'13:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'15:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'17:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'19:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'21:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'23:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},

	'00:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'04:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'08:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'12:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'16:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'20:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},

	'00:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'04:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'08:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'12:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'16:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'20:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},

	'00:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'04:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'08:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'12:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'16:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'20:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},

	'00:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'04:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'08:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'12:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'16:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'20:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},

	'02:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'06:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'10:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'14:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'18:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'22:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},

	'01:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'05:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'09:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'13:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'17:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'21:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},

	'16:00': {'title': 'Kundun', 'message': 'Precisa de convite: Lost Map (Kalima)'},
	'21:00': {'title': 'Erohin', 'message': 'LAND OF TRIALS, precisa ser membro de guild vencedora do CS'},
	'21:00': {'title': 'Balgass', 'message': 'CRYWOLF'},
	'16:00': {'title': 'Balgass', 'message': 'RAKLION HATCHERY'},
	'19:00': {'title': 'Tesouro Loren', 'message': 'Todos os servers'},
	'23:00': {'title': 'Invocação de boss', 'message': 'Server 1'},
	'22:00': {'title': 'Ataque zumbi', 'message': 'Server 1'},
}

// TERÇA
eventos[2] = {
	'20:00': {'title': 'MEGADROP', 'message': 'Todos os servers, lorencia (140, 125)'},
	'00:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'02:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'04:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'06:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'08:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'10:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'12:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'14:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'16:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'18:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'20:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'22:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},

	'01:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'03:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'05:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'07:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'09:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'11:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'13:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'15:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'17:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'19:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'21:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'23:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},

	'01:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'03:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'05:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'07:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'09:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'11:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'13:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'15:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'17:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'19:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'21:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'23:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},

	'00:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'04:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'08:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'12:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'16:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'20:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},

	'00:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'04:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'08:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'12:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'16:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'20:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},

	'00:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'04:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'08:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'12:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'16:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'20:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},

	'00:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'04:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'08:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'12:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'16:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'20:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},

	'02:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'06:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'10:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'14:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'18:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'22:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},

	'01:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'05:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'09:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'13:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'17:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'21:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},

	'16:00': {'title': 'Kundun', 'message': 'Precisa de convite: Lost Map (Kalima)'},
	'21:00': {'title': 'Erohin', 'message': 'LAND OF TRIALS, precisa ser membro de guild vencedora do CS'},
	'22:00': {'title': 'Medusa', 'message': 'PEACE SWAMP'},
	'21:00': {'title': 'Tesouro Loren', 'message': 'Todos os servers'},
	'23:00': {'title': 'Invocação de boss', 'message': 'Server 1'},
	'22:00': {'title': 'Ataque zumbi', 'message': 'Server 1'},
}

// QUARTA
eventos[3] = {
	'20:00': {'title': 'MEGADROP', 'message': 'Todos os servers, lorencia (140, 125)'},
	'00:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'02:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'04:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'06:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'08:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'10:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'12:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'14:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'16:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'18:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'20:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'22:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},

	'01:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'03:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'05:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'07:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'09:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'11:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'13:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'15:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'17:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'19:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'21:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'23:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},

	'01:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'03:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'05:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'07:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'09:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'11:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'13:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'15:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'17:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'19:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'21:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'23:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},

	'00:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'04:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'08:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'12:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'16:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'20:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},

	'00:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'04:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'08:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'12:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'16:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'20:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},

	'00:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'04:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'08:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'12:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'16:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'20:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},

	'00:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'04:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'08:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'12:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'16:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'20:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},

	'02:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'06:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'10:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'14:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'18:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'22:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},

	'01:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'05:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'09:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'13:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'17:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'21:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},

	'16:00': {'title': 'Kundun', 'message': 'Precisa de convite: Lost Map (Kalima)'},
	'21:00': {'title': 'Erohin', 'message': 'LAND OF TRIALS, precisa ser membro de guild vencedora do CS'},
	'21:00': {'title': 'Balgass', 'message': 'CRYWOLF'},
	'18:00': {'title': 'Balgass', 'message': 'RAKLION HATCHERY'},
	'23:00': {'title': 'Tesouro Loren', 'message': 'Todos os servers'},
	'23:00': {'title': 'Invocação de boss', 'message': 'Server 1'},
	'22:00': {'title': 'Ataque zumbi', 'message': 'Server 1'},
}

// QUINTA
eventos[4] = {
	'20:00': {'title': 'MEGADROP', 'message': 'Todos os servers, lorencia (140, 125)'},
	'00:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'02:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'04:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'06:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'08:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'10:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'12:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'14:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'16:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'18:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'20:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'22:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},

	'01:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'03:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'05:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'07:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'09:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'11:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'13:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'15:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'17:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'19:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'21:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'23:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},

	'01:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'03:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'05:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'07:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'09:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'11:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'13:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'15:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'17:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'19:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'21:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'23:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},

	'00:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'04:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'08:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'12:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'16:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'20:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},

	'00:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'04:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'08:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'12:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'16:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'20:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},

	'00:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'04:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'08:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'12:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'16:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'20:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},

	'00:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'04:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'08:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'12:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'16:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'20:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},

	'02:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'06:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'10:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'14:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'18:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'22:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},

	'01:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'05:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'09:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'13:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'17:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'21:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},

	'16:00': {'title': 'Kundun', 'message': 'Precisa de convite: Lost Map (Kalima)'},
	'21:00': {'title': 'Erohin', 'message': 'LAND OF TRIALS, precisa ser membro de guild vencedora do CS'},
	'22:00': {'title': 'Medusa', 'message': 'PEACE SWAMP'},
	'16:00': {'title': 'Tesouro Loren', 'message': 'Todos os servers'},
	'23:00': {'title': 'Invocação de boss', 'message': 'Server 1'},
	'22:00': {'title': 'Ataque zumbi', 'message': 'Server 1'},
}

// SEXTA
eventos[5] = {
	'20:00': {'title': 'MEGADROP', 'message': 'Todos os servers, lorencia (140, 125)'},
	'00:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'02:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'04:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'06:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'08:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'10:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'12:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'14:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'16:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'18:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'20:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'22:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},

	'01:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'03:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'05:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'07:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'09:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'11:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'13:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'15:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'17:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'19:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'21:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'23:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},

	'01:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'03:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'05:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'07:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'09:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'11:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'13:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'15:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'17:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'19:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'21:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'23:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},

	'00:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'04:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'08:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'12:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'16:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'20:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},

	'00:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'04:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'08:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'12:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'16:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'20:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},

	'00:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'04:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'08:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'12:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'16:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'20:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},

	'00:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'04:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'08:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'12:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'16:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'20:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},

	'02:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'06:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'10:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'14:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'18:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'22:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},

	'01:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'05:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'09:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'13:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'17:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'21:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},

	'16:00': {'title': 'Kundun', 'message': 'Precisa de convite: Lost Map (Kalima)'},
	'21:00': {'title': 'Erohin', 'message': 'LAND OF TRIALS, precisa ser membro de guild vencedora do CS'},
	'16:00': {'title': 'Balgass', 'message': 'RAKLION HATCHERY'},
	'19:00': {'title': 'Tesouro Loren', 'message': 'Todos os servers'},
	'23:00': {'title': 'Invocação de boss', 'message': 'Server 1'},
	'22:00': {'title': 'Ataque zumbi', 'message': 'Server 1'},
}

// SÁBADO
eventos[6] = {
	'20:00': {'title': 'MEGADROP', 'message': 'Todos os servers, lorencia (140, 125)'},
	'00:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'02:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'04:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'06:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'08:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'10:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'12:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'14:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'16:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'18:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'20:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},
	'22:30': {'title': 'Blood Castle', 'message': 'Precisa de convite: Invisibility Cloak'},

	'01:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'03:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'05:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'07:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'09:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'11:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'13:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'15:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'17:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'19:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'21:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},
	'23:00': {'title': 'Chaos Castle', 'message': 'Precisa de convite: Armor of Guardsman (Vende no bar de lorencia)'},

	'01:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'03:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'05:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'07:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'09:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'11:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'13:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'15:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'17:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'19:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'21:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},
	'23:30': {'title': 'Devil Square', 'message': 'Precisa de convite: Invitation to Devil Square'},

	'00:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'04:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'08:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'12:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'16:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},
	'20:05': {'title': 'Skeleton King', 'message': 'Todos os servers, lorencia e noria'},

	'00:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'04:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'08:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'12:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'16:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},
	'20:15': {'title': 'Red Dragon', 'message': 'Todos os servers, lorencia, noria, devias, icarus'},

	'00:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'04:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'08:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'12:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'16:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},
	'20:50': {'title': 'White Wizard', 'message': 'Todos os servers, lorencia, noria, devias'},

	'00:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'04:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'08:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'12:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'16:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},
	'20:25': {'title': 'Dragão dourado', 'message': 'Todos os servers, todos os mapas'},

	'02:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'06:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'10:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'14:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'18:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},
	'22:15': {'title': 'Moon Rabbit', 'message': 'Todos os servers, todos os mapas'},

	'01:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'05:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'09:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'13:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'17:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},
	'21:25': {'title': 'Invasão de demonios', 'message': 'Todos os servers, Tarkan, Aida, Kanturu, Karutan, Acheron.'},

	'16:00': {'title': 'Kundun', 'message': 'Precisa de convite: Lost Map (Kalima)'},
	'21:00': {'title': 'Erohin', 'message': 'LAND OF TRIALS, precisa ser membro de guild vencedora do CS'},
	'16:00': {'title': 'Medusa', 'message': 'PEACE SWAMP'},
	'18:00': {'title': 'Balgass', 'message': 'CRYWOLF'},
	'17:00': {'title': 'Tesouro Loren', 'message': 'Todos os servers'},
	'22:00': {'title': 'Tesouro Dung', 'message': 'Todos os servers'},
	'23:00': {'title': 'Invocação de boss', 'message': 'Server 1'},
	'19:00': {'title': 'Ataque zumbi', 'message': 'Server 1'},
	'15:00': {'title': 'Castle Siege', 'message': 'Server 1'},
}

var getEvent = function(hh, mm, now) {
    return eventos[now][hh + ':' + (mm)];
};

var notify = function(message, title = 'Evento') {
    var option = {
        type: 'basic',
        title: title,
        message: message,
        iconUrl: '../../icons/bell.jpg',
    }
    chrome.notifications.create(notificationId, option, function(notificationId) {
        var mySong = new Audio('../../songs/alarm.mp3');
        mySong.play();
    });
};

var startTimer = function() {
    var notificacao = setInterval(function() {
        var now = new Date();

        var targetEvent = getEvent(now.getHours(), now.getMinutes() + 10, now.getDay());
        if (targetEvent) {
            notify(targetEvent.message, targetEvent.title  + ' EM 10MIN!');
        }

        var targetEvent = getEvent(now.getHours(), now.getMinutes() + 5, now.getDay());
        if (targetEvent) {
            notify(targetEvent.message, targetEvent.title  + ' EM 5MIN!');
        }

    }, interval);

	chrome.notifications.onClicked.addListener(function() {
		chrome.notifications.clear(notificationId);
	});
};

var main = function() {
    startTimer();
};

main();